/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MandelbrotJNI */

#ifndef _Included_MandelbrotJNI
#define _Included_MandelbrotJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MandelbrotJNI
 * Method:    computeMandelbrot
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_MandelbrotJNI_computeMandelbrot
  (JNIEnv *, jobject, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
