# Build stage
FROM maven:3.9.3-eclipse-temurin-17 AS build
WORKDIR /build
COPY pom.xml .
COPY src ./src
RUN mvn -f pom.xml clean package

# Runtime stage
FROM eclipse-temurin:17
WORKDIR /app
COPY --from=build /build/target/table-extractor.jar app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]
