#uses python image
FROM python:3.9-slim

#sets working directory in the container
WORKDIR /app

#copy python script into container
COPY app.py .

#define command to run script
CMD ["python", "app.py"]