FROM haskell::8.10

WORKDIR /app

RUN apt-get update && apt-get install -y curl

RUN curl -o page.html "https://en.wikipedia.org/wiki/List_of_largest_companies_in_the_United_States_by_revenue"

COPY project3_haskell.hs .

RUN ghc --make project3_haskell.hs -o project3_haskell && chmod +x project3_haskell

CMD ["./project3_haskell"]


