# Use an official Python runtime as the base image
FROM python:3.11

# Set the working directory inside the container
WORKDIR /app

# Copy the script into the container's working directory
COPY Hello_Paul.py .

# Define the command to run the script
ENTRYPOINT ["python", "/app/Hello_Paul.py"]
