# Use Maven with OpenJDK
FROM maven:3.8.5-openjdk-17 AS build

# Set the working directory
WORKDIR /app/project

# Copy the project files
COPY . .

# Build the project
RUN mvn clean package -DskipTests \
    -Dxtend.outputDirectory=/app/project/target/generated-sources/xtend


# Use a minimal OpenJDK image for the runtime
FROM openjdk:17-slim

# Set the working directory
WORKDIR /app

# Copy the compiled JAR from the build stage
COPY --from=build /app/project/target/table-extractor.jar /app/table-extractor.jar

# Expose the application port
EXPOSE 8080

# Run the application
CMD ["java", "-jar", "table-extractor.jar"]
